"""Initial schema with indexes and cascading

Revision ID: 41f3b0f7bb74
Revises: 
Create Date: 2026-08-17 07:57:53.333785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f3b0f7bb74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_notifications_created', 'notifications', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('posts', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('posts', 'linkedin_urn',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index('idx_posts_status_scheduled', 'posts', ['status', 'scheduled_at'], unique=False)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'posts', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'social_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'social_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'social_accounts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'campaigns', ['campaign_id'], ['id'])
    op.drop_index('idx_posts_status_scheduled', table_name='posts')
    op.alter_column('posts', 'linkedin_urn',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('posts', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.drop_index('idx_notifications_created', table_name='notifications')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
